FROM node:14.19.1
RUN rm -rf node_modules \
&& npm install \
&& npm update \
&& npm install pm2 -g
EXPOSE 2400
WORKDIR .
CMD pm2 start server.js
Data evangelists are modern day crusaders of gathering and leveraging data insights. Data evangelists possess deep technical skill to solve complex problems with the use of interdisciplinary fields, processes, and algorithms to extract insights from structured and unstructured data.28 sept. 2020